# Project information
site_name: KFormMaster Docs
site_description: Documentation for the KFormMaster Android library
site_author: TheJuki
site_url: https://thejuki.github.io/KFormMaster/

# Repository
repo_name: 'TheJuki/KFormMaster'
repo_url: 'https://github.com/thejuki/KFormMaster'
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2020 Justin Kirk'

# Configuration
theme:
  name: material
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/KF.png'

# Extensions
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

# Navigation tree
nav:
  - Home:
      - 'Getting Started': 'index.md'
      - 'Form Build Helper': 'helper.md'
      - 'Migrate from Builders': 'migrateBuilder.md'
  - Form Elements:
      - 'Base': 'element/base.md'
      - 'Header': 'element/header.md'
      - 'Image View': 'element/imageView.md'
      - 'Single Line': 'element/singleLine.md'
      - 'Multi Line': 'element/multiLine.md'
      - 'Email': 'element/email.md'
      - 'Password': 'element/password.md'
      - 'Number': 'element/number.md'
      - 'Phone': 'element/phone.md'
      - 'Text View': 'element/textView.md'
      - 'Label': 'element/label.md'
      - 'Date': 'element/date.md'
      - 'Time': 'element/time.md'
      - 'DateTime': 'element/dateTime.md'
      - 'InlineDatePicker': 'element/inlineDatePicker.md'
      - 'Dropdown': 'element/dropDown.md'
      - 'MultiCheckBox': 'element/multiCheckBox.md'
      - 'AutoComplete': 'element/autoComplete.md'
      - 'AutoCompleteToken': 'element/autoCompleteToken.md'
      - 'Switch': 'element/switch.md'
      - 'Slider': 'element/slider.md'
      - 'CheckBox': 'element/checkBox.md'
      - 'Progress': 'element/progress.md'
      - 'Segmented': 'element/segmented.md'
      - 'SegmentedInlineTitle': 'element/segmentedInlineTitle.md'
      - 'Button': 'element/button.md'
  - Custom:
      - 'Customize Form': 'custom/customize.md'
      - 'Custom Element': 'custom/element.md'
      - 'Form Layouts': 'custom/formLayouts.md'
      - 'Google Place Autocomplete': 'custom/placeAutocomplete.md'
  - About:
      - 'Contributing': 'about/contributing.md'
      - 'Credits': 'about/credits.md'
      - 'License': 'about/license.md'